Main site components
vapor/design pull request #104
Opened 2023-07-23 09:05 UTC by ptoffy

2023-07-25 17:36 UTC, 0xTim requested changes
This is a great start and overall looks fine. Can you pull in the latest changes for highlight.js? (We might need to update the docs as well for the new Leaf changes)

Main issue is we need CI to go green to be able to check out the changes

2023-08-07 13:51 UTC, 0xTim requested changes
Ok this is really awesome! I have a few requests, mainly around the use of `rgba()` with hardcoded rgb values instead of SASS variables.

Finally, there are a couple of things we need to fix.

1. As the nabber for the homepage will be fixed (and likely on other pages) we should add a new CSS class for `fixed-navbar` that sets the Z value so it sits on top of everything and set the background correctly (see below)

<img width="2035" alt="Screenshot 2023-08-07 at 14 37 59" src="https://github.com/vapor/design/assets/9938337/ced67720-d31d-4aef-9155-26cb818e2a07">

2. Second, the hero image on the blog page has changed. It should be different on the main page and the same on all the other pages IIRC. See below

<img width="2035" alt="Screenshot 2023-08-07 at 14 39 20" src="https://github.com/vapor/design/assets/9938337/e29403b6-fa57-4b90-a780-35095cef5a98">

Finally, we have a few fixes for mobile to do.

1. Sponsors section needs mobile design added 
<img width="2035" alt="Screenshot 2023-08-07 at 14 49 09" src="https://github.com/vapor/design/assets/9938337/303e5bf1-4eda-478e-accc-d7bcb7831aba">

2. Spacing throughout can be tightened up, e.g.

<img width="2035" alt="Screenshot 2023-08-07 at 14 48 49" src="https://github.com/vapor/design/assets/9938337/3977e2a6-c40a-4c7c-aa45-e25becbc070b">

Finally, these should be centered:
<img width="2035" alt="Screenshot 2023-08-07 at 14 49 02" src="https://github.com/vapor/design/assets/9938337/e0c0406c-920d-4bf9-9495-d28a5b34aad3">

Awesome work though!

2023-08-07 13:51 UTC, 0xTim commented on stack.yml
Pretty sure we refer to this in our deploy pipeline so that needs updating for the new name

2023-08-07 13:51 UTC, 0xTim commented on Sources/DesignSite/DesignTheme.swift
> +                        Span("Integrations").style("color: #DF3FEB")
This should be set externally in CSS as a colour variable

2023-08-07 13:51 UTC, 0xTim commented on Sources/DesignSite/DesignTheme.swift
> +                        H2("Full integration with your entire stack").style("margin-top: 8px;")
Just an FYI - inline CSS will be disabled so this should be tagged with an ID and set in CSS

2023-08-07 13:51 UTC, 0xTim commented on static/js/mainSiteScrollNavbar.js
> +        document.querySelector(".navbar").style.top = "-80px";
I this done this way to make it 'bounce' in instead of setting the display property?

2023-08-07 13:51 UTC, 0xTim commented on src/scss/vapor/main-site.scss
> +        background: linear-gradient(230.51deg, rgba(35, 172, 240, 0.25) 27.41%, rgba(223, 62, 251, 0.25) 67%, rgba(112, 25, 128, 0.25) 80.12%);
I have been extracting out these rgba values into our colours so they look something like `rgba($grey-100, 0.25)`, would be great if you could do that here where you're using RGBA unless they don't line up with any hex values we have

2023-08-07 13:51 UTC, 0xTim commented on src/scss/vapor/main-site.scss
> +            background: rgba(178, 35, 95, 0.1);
Use a SASS variable here

2023-08-07 13:51 UTC, 0xTim commented on src/scss/vapor/main-site.scss
> +            // background: rgba(128, 25, 68, 0.3);
Delete

2023-08-07 13:51 UTC, 0xTim commented on src/scss/vapor/main-site.scss
> +        // overflow-x: hidden;
Remove if not needed

2024-03-31 13:55 UTC, ptoffy commented on src/scss/vapor/main-site.scss
> +        background: linear-gradient(230.51deg, rgba(35, 172, 240, 0.25) 27.41%, rgba(223, 62, 251, 0.25) 67%, rgba(112, 25, 128, 0.25) 80.12%);
IMO this specific one is fine as it is because it's a gradient, the colours inside are specific to create this gradient and unlikely to be reused

2024-04-08 15:04 UTC, 0xTim approved these changes

2024-04-09 11:27 UTC, 0xTim approved these changes
I have a couple of things I'd like to improve but they can be done in a separate PR - I'll create issues for those to track

2024-05-13 10:09 UTC, merged