Finalise some main site styles
vapor/design pull request #190
Opened 2024-06-15 15:22 UTC by ptoffy

2024-06-16 23:00 UTC, 0xTim requested changes
Looks good other than the new line bracket formatting

2024-06-16 23:00 UTC, 0xTim commented on src/scss/vapor/main-site.scss
> +        color: $code-explainer-title;
Nice

2024-06-16 23:01 UTC, 0xTim commented on Sources/DesignSite/DesignTheme.swift
> +                               let name: String = try req.query.get(at: "name")
Ah I get the intention - ignore me

2024-06-17 05:20 UTC, ptoffy commented on Sources/DesignSite/DesignTheme.swift
> +                                 .filter(\\.$number == name)
[`get`](https://github.com/vapor/vapor/blob/main/Sources/Vapor/Content/URLQueryContainer.swift#L71) doesn't return an optional, that's the `subscript`, so all good there

2024-06-17 08:38 UTC, 0xTim approved these changes

2024-06-17 08:46 UTC, merged