Make scrolling more generic
vapor/design pull request #201
Opened 2024-07-15 15:45 UTC by ptoffy

This allows to use the scrolling buttons all over the page rather than just in the showcase

2024-07-15 16:04 UTC, 0xTim requested changes
Lets keep the number of sponsors at 3 and only show the buttons when the page size means they run off the screen

2024-07-15 16:05 UTC, ptoffy commented
@0xTim I added sponsors to be able to see how scrolling works when there are more

2024-07-15 16:06 UTC, 0xTim commented
Ok we can test the hiding on the main page then. Other option is move the sponsors card to the design page that contains all the elements

2024-07-15 16:07 UTC, 0xTim approved these changes

2024-07-17 11:31 UTC, 0xTim requested changes

2024-07-17 11:31 UTC, 0xTim commented on src/scss/vapor/main-site.scss
> +        &.disabled {
We need dark mode versions of the disabled state

2024-07-17 16:17 UTC, 0xTim approved these changes
Looks good!

2024-07-17 16:25 UTC, merged